on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  container-test:
    name: Container Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Push Tag
      if: ${{github.ref_type == 'tag' }}
      uses: docker/build-push-action@v3
      with:
        context: .
        file: "${{github.workspace}}/docker/go/Dockerfile"
        push: true
        tags: |
          ${{github.repository}}:${{github.ref_name}}
    - name: Build and Push Branch
      if: ${{github.ref_type == 'branch' }}
      uses: docker/build-push-action@v3
      with:
        context: .
        file: "${{github.workspace}}/docker/go/Dockerfile"
        push: true
        tags: |
          ${{github.repository}}:${{github.ref_name}}-${{github.run_number}}
          ${{github.repository}}:${{github.ref_name}}-latest
