on:
  workflow_call:

jobs:
  container-test:
    name: Container Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Only
      uses: docker/build-push-action@v3
      with:
        context: .
        file: "{{context}}/docker/go/Dockerfile"
        push: false
        tags: |
          build-test
          ${{github.workspace}}:${{github.ref_name}}
          ${{github.workspace}}:${{github.ref_name}}-${{github.run_number}}
          ${{github.workspace}}:${{github.ref_name}}-latest
