on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  container-test:
    name: Container Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push Tag
      if: ${{ GITHUB_REF_TYPE == 'tag' }}
      uses: docker/build-push-action@v3
      with:
        context: .
        file: docker/go/Dockerfile
        push: true
        tags: |
          ${{GITHUB_WORKSPACE}}:${{GITHUB_REF_NAME}}
    - name: Build and Push Branch
      if: ${{ GITHUB_REF_TYPE == 'branch' }}
      uses: docker/build-push-action@v3
      with:
        context: .
        file: {context}/docker/go/Dockerfile
        push: true
        tags: |
          ${{GITHUB_WORKSPACE}}:${{GITHUB_REF_NAME}}-${{GITHUB_RUN_NUMBER}}
          ${{GITHUB_WORKSPACE}}:${{GITHUB_REF_NAME}}-latest
