on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DEPLOYER_EMAIL:
        required: true
      DEPLOYER_USERNAME:
        required: true
      DEPLOYER_GITHUB_TOKEN:
        required: true
    inputs:
      push-image:
        description: Pushes built image to dockerhub when set to true.
        required: false
        type: boolean
        default: false
      skip-deploy:
        description: Prevents modifications to apps-infrastructure when set to true. Primarily for testing.
        required: false
        type: boolean
        default: false
      dockerfile:
        description: Path to the Dockerfile
        required: true
        type: string
      tags:
        description: List of tags for the image (must be all lowercase). These will override the default tags.
        required: false
        type: string
      environment:
        description: The target environment to build and deploy image
        required: true
        default: dev
        type: string
      project-name:
        description: The name of the project to deploy build to
        required: true
        default: web-app
        type: string
      cdn-path:
        description: Path where stored static files in CDN
        default: web-app
        type: string
    outputs:
      image-tag:
        value: ${{ jobs.build-image.outputs.image-tag }}

jobs:
  build-image:
    name: Build
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      IMAGE_TAGS: ${{ inputs.tags }}
    outputs:
      image-tag: ${{ steps.generate-image-tags.outputs.IMAGE_TAG }}
    steps:
      - uses: actions/checkout@v3
#      - uses: actions/download-artifact@v3
#        with:
#          name: artifact-${{ inputs.project-name }}-${{inputs.environment}}-${{ github.sha }}
#          path: ~/
      - name: Short SHA
        if: inputs.push-image && env.IMAGE_TAGS == ''
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)-${{inputs.environment}}" >> $GITHUB_ENV
      - id: generate-image-tags
        # Do not overwrite tags if set already from input
        if: inputs.push-image && env.IMAGE_TAGS == ''
        # We're pushing an image and no tags supplied, so create defaults
        run: |
          echo "IMAGE_TAGS<<EOF" >> $GITHUB_ENV
          echo "${{github.repository_owner}}/${{inputs.project-name}}:${{env.SHORT_SHA}}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{github.repository_owner}}/${{inputs.project-name}}:${{env.SHORT_SHA}}" >> $GITHUB_OUTPUT
      - name: Setup SSH
        run: |
          mkdir -p -m 0700 "$HOME/.ssh"
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.GO_PRIVATE_REPO_KEY }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Info
        run: |
          echo "Push Image: ${{inputs.push-image}}"
          echo "Tags: ${{env.IMAGE_TAGS}}"
      - name: Build image and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: /home/runner/
          file: ${{ inputs.dockerfile }}
          tags: ${{ env.IMAGE_TAGS }}
          push: ${{ inputs.push-image }}
          ssh: default
          build-args: |
            CDN_PATH=${{ inputs.cdn-path }}
      - name: Image digest
        run: echo "::notice ::Image digest ${{ steps.docker_build.outputs.digest }}"

      - name: Run Trivy vulnerability scanner
        if: inputs.push-image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{env.IMAGE_TAGS}}
          format: "json"
          output: "trivy-results.json"
          ignore-unfixed: true
          timeout: 10m
        env:
          TRIVY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v3
        if: inputs.push-image
        with:
          name: Security Report
          path: trivy-results.json
          retention-days: 5

      - name: Checkout Workflows Repo
        if: inputs.push-image
        uses: actions/checkout@v3
        with:
          repository: "toggleglobal/workflows"
          token: ${{ secrets.DEPLOYER_GITHUB_TOKEN }}
          path: workflows

      - name: Run Trivy Parser
        id: trivy-parser
        if: inputs.push-image
        run: ./workflows/.github/workflows/scripts/trivyresult_parser.sh trivy-results.json
        shell: bash

      - name: Fail with Critical
        if: inputs.push-image && steps.trivy-parser.outputs.stdout == 1
        run: exit 1

      - name: Checkout Chart
        if: inputs.push-image && !inputs.skip-deploy
        uses: actions/checkout@v3
        with:
          repository: "toggleglobal/apps-infrastructure"
          token: ${{ secrets.DEPLOYER_GITHUB_TOKEN }}
          path: apps-infrastructure

      - name: Setup git
        if: inputs.push-image && !inputs.skip-deploy
        run: |
          git config --global user.email "${{ secrets.DEPLOYER_EMAIL }}"
          git config --global user.name "${{ secrets.DEPLOYER_USERNAME }}"
      - name: Update image tag
        if: inputs.push-image && !inputs.skip-deploy
        run: |
          cd apps-infrastructure
          CHART_VALUES_PATH="./charts/${{ inputs.project-name }}/values"
          printf "common:\n  image:\n    tag: \"${{env.SHORT_SHA}}\"\n" > "${CHART_VALUES_PATH}/image-${{inputs.environment}}.yaml"
      - name: Commit new image
        env:
          GH_TOKEN: ${{ secrets.DEPLOYER_GITHUB_TOKEN }}
        if: inputs.push-image && !inputs.skip-deploy
        run: |
          cd apps-infrastructure
          git add .
          if git status | grep -q "Changes to be committed"
          then
            if [[ ${{inputs.environment}} == "prod" ]]; then
              BRANCH_NAME="${{ inputs.project-name }}-${GITHUB_RUN_ID}"
              git checkout -b ${BRANCH_NAME}
              git commit --message "Promote to ${{ inputs.environment }} from ${{ inputs.project-name }}"
              echo "Pushing git commit"
              git push -u origin ${BRANCH_NAME}
              echo "Creating a pull request"
              gh pr create -t "Promote to ${{ inputs.environment }} ${{ inputs.project-name }}" -B "main" -b "Promote to production ${{ inputs.project-name }}" -H ${BRANCH_NAME}
            else
              git commit --message "Update ${{ inputs.environment }} env image ${{ inputs.project-name }}"
              echo "Pushing git commit"
              git push -u origin main
            fi
          else
            echo "No changes detected"
          fi
