on:
  workflow_call:
    secrets:
      # PYTHON_PRIVATE_REPO_KEY is the only secret required for all situations.
      # The others are only used when 'push-image' input is true; where the
      # image is actually pushed to Dockerhub and the Infrastructure Chart
      # is updated with latest tag.
      PYTHON_PRIVATE_REPO_KEY:
        required: true
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false
      DEPLOYER_EMAIL:
        required: false
      DEPLOYER_USERNAME:
        required: false
      DEPLOYER_GITHUB_TOKEN:
        required: false

    inputs:
      push-image:
        description: Pushes built image to dockerhub when set to true.
        required: false
        type: boolean
        default: false
      is-poc:
        description: Use poc environment to deploy if set to true
        required: false
        type: boolean
        default: false
      dockerfile:
        description: Path to the Dockerfile
        required: true
        type: string
      skip-deploy:
        description: Prevents modifications to apps-infrastructure when set to true. Primarily for testing.
        required: false
        type: boolean
        default: false
      tags:
        description: List of tags for the image (must be all lowercase). These will override the default tags.
        required: false
        type: string
      repository-suffix:
        description: >
          Adds a hyphen separated suffix to the repository name used to create image tags (must be all lowercase).
          This is primarily for use where a repository has more than one Dockerfile. This is ignored if tags has been set.
        required: false
        type: string
      python-version:
        description: Version of python used during build if specified as argument in Dockerfile
        required: false
        type: string
      runs-as:
        description: Defines how the built image is expected to be run, e.g service or cronjob.
        default: service
        required: false
        type: string
      git-lfs:
        description: Set to true if using Git LFS
        default: false
        required: false
        type: boolean
    outputs:
      image-tag:
        value: ${{ jobs.build-push-image.outputs.image-tag }}

jobs:
  build-push-image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      IMAGE_TAGS: ${{ inputs.tags }}
      PYTHON_VERSION: ${{ inputs.python-version }}
      REPOSITORY_SUFFIX: ${{ inputs.repository-suffix }}
    outputs:
      image-tag: ${{ steps.gen-ref.outputs.IMAGE_TAG }}
      image-ref: ${{ steps.gen-ref.outputs.IMAGE_REF }}
      short-sha: ${{ steps.short-sha.outputs.SHORT_SHA }}
      repository-suffix: ${{ steps.repo-suffix.outputs.REPOSITORY_SUFFIX }}
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          # all of these default to true in action
          # we want to delete only unused runtimes here
          tool-cache: false
          docker-images: false
          large-packages: false
          swap-storage: false
          android: true
          dotnet: true
          haskell: true

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: ${{ inputs.git-lfs }}

      - name: Short SHA
        id: short-sha
        if: inputs.push-image && env.IMAGE_TAGS == ''
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Repository Suffix
        id: repo-suffix
        # Prepend hyphen if set
        if: env.REPOSITORY_SUFFIX != ''
        run: |
          REPOSITORY_SUFFIX=-${{env.REPOSITORY_SUFFIX}}
          echo "REPOSITORY_SUFFIX=$REPOSITORY_SUFFIX" >> $GITHUB_ENV
          echo "REPOSITORY_SUFFIX=$REPOSITORY_SUFFIX" >> $GITHUB_OUTPUT

      - name: Generate Image Tags
        id: gen-ref
        # Do not overwrite tags if set already from input
        if: inputs.push-image && env.IMAGE_TAGS == ''
        # We're pushing an image and no tags supplied, so create defaults
        run: |
          echo "IMAGE_TAGS<<EOF" >> $GITHUB_ENV
          echo "${{github.repository}}${{env.REPOSITORY_SUFFIX}}:${{env.SHORT_SHA}}" >> $GITHUB_ENV
          echo "${{github.repository}}${{env.REPOSITORY_SUFFIX}}:${{github.ref_name}}-latest" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "IMAGE_REF=${{github.repository}}${{env.REPOSITORY_SUFFIX}}:${{env.SHORT_SHA}}" >> $GITHUB_OUTPUT

      - name: Setup SSH
        run: |
          mkdir -p -m 0700 "$HOME/.ssh"
          ssh-keyscan -H github.com >> $HOME/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.PYTHON_PRIVATE_REPO_KEY }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to DockerHub
        if: inputs.push-image
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Info
        run: |
          echo "Push Image: ${{inputs.push-image}}"
          echo "Tags: ${{env.IMAGE_TAGS}}"
          echo "Python Version: ${{env.PYTHON_VERSION}}}"
          echo "Short-SHA: ${{env.SHORT_SHA}}"
          echo "Repository-suffix: ${{env.REPOSITORY_SUFFIX}}"

      - name: Build image and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          tags: ${{ env.IMAGE_TAGS }}
          push: ${{ inputs.push-image }}
          ssh: default
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}

      - name: Image digest
        run: echo "::notice ::Image digest ${{ steps.docker_build.outputs.digest }}"

  scan-image:
    needs: [ build-push-image ]
    if: inputs.push-image
    secrets: inherit
    uses: toggleglobal/workflows/.github/workflows/vulnerability-scanner.yml@main
    with:
      image: ${{ needs.build-push-image.outputs.image-ref }}

  update-app-chart:
    needs: [ build-push-image, scan-image ]
    if: inputs.push-image && !inputs.skip-deploy
    secrets: inherit
    uses: toggleglobal/workflows/.github/workflows/update-app-chart.yml@main
    with:
      runs-as: ${{ inputs.runs-as }}
      short-sha: ${{ needs.build-push-image.outputs.short-sha }}
      repository-suffix: ${{ needs.build-push-image.outputs.repository-suffix }}