on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DEPLOYER_EMAIL:
        required: true
      DEPLOYER_USERNAME:
        required: true
      DEPLOYER_GITHUB_TOKEN:
        required: true
    inputs:
      push-image:
        description: Pushes built image to dockerhub when set to true.
        required: false
        type: boolean
        default: false
      skip-deploy:
        description: Prevents modifications to apps-infrastructure when set to true. Primarily for testing.
        required: false
        type: boolean
        default: false
      dockerfile:
        description: Path to the Dockerfile
        required: true
        type: string
      next-public-ga:
        description: Next public ga
        required: true
        type: string
      next-public-naver:
        description: Next public naver
        required: true
        type: string
      next-public-domain:
        description: Next public domain
        required: true
        type: string
      next-public-cookie-pro:
        description: Next public cookie pro
        required: true
        type: string
      environment:
        description: The target environment to build and deploy image
        required: true
        default: dev
        type: string
      cdn-path:
        description: Path where stored static files in CDN
        default: website
        type: string
    outputs:
      image-tag:
        value: ${{ jobs.build-image.outputs.image-tag }}
      image:
        value: ${{ jobs.build-image.outputs.image }}

jobs:
  build-push-image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      NEXT_PUBLIC_GA: ${{ inputs.next-public-ga }}
      NEXT_PUBLIC_NAVER: ${{  inputs.next-public-naver }}
      NEXT_PUBLIC_DOMAIN: ${{ inputs.next-public-domain }}
      NEXT_PUBLIC_COOKIE_PRO: ${{ inputs.next-public-cookie-pro }}
    outputs:
      image: ${{ steps.generate-image-tags.outputs.IMAGE }}
      image-tag: ${{ steps.generate-image-tags.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - id: generate-image-tags
        if: inputs.push-image
        run: |
          IMAGE_TAG="$(git rev-parse --short HEAD)-${{ github.run_number }}-${{inputs.environment}}"
          IMAGE="${{github.repository}}:$IMAGE_TAG"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Setup SSH
        run: |
          mkdir -p -m 0700 "$HOME/.ssh"
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.GO_PRIVATE_REPO_KEY }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Info
        run: |
          echo "Push Image: ${{inputs.push-image}}"
          echo "Image: ${{env.IMAGE}}"
      - name: Build image and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          tags: ${{ env.IMAGE }}
          push: ${{ inputs.push-image }}
          ssh: default
          build-args: |
            NEXT_PUBLIC_GA=${{ env.NEXT_PUBLIC_GA }}
            NEXT_PUBLIC_NAVER=${{  env.NEXT_PUBLIC_NAVER }}
            NEXT_PUBLIC_DOMAIN=${{ env.NEXT_PUBLIC_DOMAIN }}
            NEXT_PUBLIC_COOKIE_PRO=${{ env.NEXT_PUBLIC_COOKIE_PRO }}
            WEB_SITE_LOCALAZY_READ_KEY=${{ secrets.WEB_SITE_LOCALAZY_READ_KEY }}
            WEB_SITE_LOCALAZY_WRITE_KEY=${{ secrets.WEB_SITE_LOCALAZY_WRITE_KEY }}
            NEXT_VERSION=${{ github.sha }}-${{ github.run_number }}
            CDN_PATH=${{ inputs.cdn-path }}
      - name: Image digest
        run: echo "::notice ::Image digest ${{ steps.docker_build.outputs.digest }}"

  scan-image:
    needs: [ build-push-image ]
    if: inputs.push-image
    secrets: inherit
    uses: toggleglobal/workflows/.github/workflows/vulnerability-scanner.yml@main
    with:
      image: ${{ needs.build-push-image.outputs.image }}

  update-app-chart:
    needs: [ build-push-image, scan-image ]
    if: inputs.push-image && !inputs.skip-deploy
    secrets: inherit
    uses: toggleglobal/workflows/.github/workflows/update-app-chart.yml@main
    with:
      runs-as: inputs.runs-as
      short-sha: ${{ needs.build-push-image.outputs.image-tag }}
      environment: ${{ inputs.environment }}