on:
  workflow_call:
    secrets:
      DEPLOYER_EMAIL:
        required: true
      DEPLOYER_USERNAME:
        required: true
      DEPLOYER_GITHUB_TOKEN:
        required: true
    inputs:
      repository-suffix:
        description: >
          Adds a hyphen separated suffix to the repository name used to create image tags (must be all lowercase).
          This is primarily for use where a repository has more than one Dockerfile. This is ignored if tags has been set.
        required: false
        type: string

jobs:
  promote-to-prod:
    env:
      REPOSITORY_SUFFIX: ${{ inputs.repository-suffix }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "toggleglobal/apps-infrastructure"
          token: ${{ secrets.DEPLOYER_GITHUB_TOKEN }}
          path: apps-infrastructure
      - name: setup git
        run: |
          git config --global user.email "${{ secrets.DEPLOYER_EMAIL }}"
          git config --global user.name "${{ secrets.DEPLOYER_USERNAME }}"
      - name: Repository Suffix
        # Prepend hyphen if set
        if: env.REPOSITORY_SUFFIX != ''
        run: |
          echo "REPOSITORY_SUFFIX=-${{env.REPOSITORY_SUFFIX}}" >> $GITHUB_ENV
      - name: update image tag prod
        run: |
          cd apps-infrastructure
          CHART_VALUES_PATH="./charts/${{ github.event.repository.name }}${{env.REPOSITORY_SUFFIX}}/values"
          cp "${CHART_VALUES_PATH}/image-dev.yaml" "${CHART_VALUES_PATH}/image-prod.yaml"
      - name: create pr
        env:
          GH_TOKEN: ${{ secrets.DEPLOYER_GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ github.event.repository.name }}-${GITHUB_RUN_ID}${{env.REPOSITORY_SUFFIX}}"
          cd apps-infrastructure
          git checkout -b ${BRANCH_NAME}
          git add .
          if git status | grep -q "Changes to be committed"
          then
            git commit --message "Promote to production from ${{ github.event.repository.name }}${{env.REPOSITORY_SUFFIX}}"
            echo "Pushing git commit"
            git push -u origin ${BRANCH_NAME}
            echo "Creating a pull request"
            gh pr create -t "Promote to production ${{ github.event.repository.name }}${{env.REPOSITORY_SUFFIX}}" -B "main" -b "Promote to production ${{ github.event.repository.name }}${{env.REPOSITORY_SUFFIX}}" -H ${BRANCH_NAME}
          else
            echo "No changes detected"
          fi
