on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      GO_PRIVATE_REPO_KEY:
        required: true

    inputs:
      branch:
        description: "Name of source branch"
        required: true
        type: string
      dockerfile:
        description: "Path to the Dockerfile"
        required: true
        type: string
      tags:
        description: "List of tags (must be all lowercase)"
        required: false
        type: string

jobs:
  push-image:
    name: Push Image
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p -m 0700 "$HOME/.ssh"
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.GO_PRIVATE_REPO_KEY }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Info
      run: |
        echo "Branch: ${{inputs.branch}}"
        echo "Tags: ${{inputs.tags}}"

    - name: Build image and push to Docker Hub
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        tags: ${{ inputs.tags }}
        # Safety check: Only push image for main branch
        push: ${{ inputs.branch == 'main' }}
        ssh: default

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

