on:
  workflow_call:
    secrets:
      DEPLOYER_EMAIL:
        required: true
      DEPLOYER_USERNAME:
        required: true
      DEPLOYER_GITHUB_TOKEN:
        required: true

jobs:
  update_image_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "toggleglobal/apps-infrastructure"
          token: ${{ secrets.DEPLOYER_GITHUB_TOKEN }}
          path: apps-infrastructure
      - name: setup git
        run: |
          git config --global user.email "${{ secrets.DEPLOYER_EMAIL }}"
          git config --global user.name "${{ secrets.DEPLOYER_USERNAME }}"
      - name: update image tag
        run: |
          IMAGE_TAG="$(git rev-parse --short HEAD)"
          cd apps-infrastructure
          CHART_VALUES_PATH="./charts/${{ github.event.repository.name }}/values"
          printf "common:\n  image:\n    tag: ${IMAGE_TAG}\n" > "${CHART_VALUES_PATH}/image-dev.yaml"
      - name: commit new image
        run: |
          cd apps-infrastructure
          git add .
          if git status | grep -q "Changes to be committed"
          then
            git commit --message "Update dev image"
            echo "Pushing git commit"
            git push -u origin main
          else
            echo "No changes detected"
          fi
