on:
  workflow_call:
    inputs:
      static-directories:
        description: Static directories to upload
        default: "[]"
        type: string
      unique-path:
        description: Path in static bucket, default should be shasum from next string template {service name}-{commit hash}-{env name}
        required: true
        type: string
      source-image:
        description: Source image
        required: true
        type: string
      static-bucket:
        description:  Bucket to upload
        required: true
        type: string
      google-creds-env:
        description:  name of the gcp credentials env
        required: true
        type: string

jobs:
  static:
    - name: Extract and upload
      runs-on: google/cloud-sdk
      strategy:
        matrix:
          static-source-path: "${{ fromJson(inputs.static-directories) }}"
      steps:
        - uses: imjasonh/setup-crane@v0.1
        - name: Extract
          run: |
            crane export ${{ inputs.source-image }} - | tar -xf - ${{ matrix.static-source-path }}
        - name: Upload
          run: gsutil rsync -r .${{ matrix.static-source-path }} gs://${{ intputs.static-bucket }}/${{ inputs.uniq-bucket-path }}/
          env:
            GOOGLE_CREDENTIALS: "${{ secrets[github.event.inputs.google-creds-env] }}"
