on:
  workflow_call:
    secrets:
      GOOGLE_CREDENTIALS:
        required: true
      STATIC_BUCKET:
        required: true

    inputs:
      static-directories:
        description: Static directories to upload
        default: "[]"
        type: string
      unique-path:
        description: Path in static bucket, default should be shasum from next string template {service name}-{commit hash}-{env name}
        required: true
        type: string

jobs:
  static:
    - name: Extract and upload
      runs-on: google/cloud-sdk
      strategy:
        matrix:
          static-source-path: "${{ fromJson(inputs.static-directories) }}"
      steps:
        - uses: imjasonh/setup-crane@v0.1
        - name: Extract
          run: |
            crane export ${{ inputs.image }} - | tar -xf - ${{ matrix.static-source-path }}
        - name: Upload
          run: gsutil rsync -r .${{ matrix.static-source-path }} gs://$STATIC_BUCKET/${{ inputs.uniq-bucket-path }}/
          env:
            GOOGLE_CREDENTIALS: "${{ secrets.GOOGLE_CREDENTIALS }}"
            STATIC_BUCKET: "${{ secrets.STATIC_BUCKET }}"
