on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DEPLOYER_GITHUB_TOKEN:
        required: true
    inputs:
      image:
        description: The image that needs to be scanned
        required: true
        type: string

jobs:
  scan-image:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image }}
          format: "json"
          output: trivy-results-${{ inputs.image }}.json
          timeout: 10m
          ignore-unfixed: true
        env:
          TRIVY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v4
        with:
          name: Security Report
          path: trivy-results-${{ inputs.image }}.json
          retention-days: 5
      - name: Checkout Workflows Repo
        uses: actions/checkout@v4
        with:
          repository: "toggleglobal/workflows"
          token: ${{ secrets.DEPLOYER_GITHUB_TOKEN }}
          path: workflows
      - name: Run Trivy Parser
        id: trivy-parser
        run: ./workflows/.github/workflows/scripts/trivyresult_parser.sh trivy-results-${{ inputs.image }}.json
        shell: bash
      - name: Fail with Critical
        if: steps.trivy-parser.outputs.stdout == 1
        run: exit 1
